# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_train.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'model_train.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11model_train.proto\x12\nmodeltrain\"\x19\n\nNumpyArray\x12\x0b\n\x03num\x18\x01 \x03(\x02\"0\n\x06Matrix\x12&\n\x06\x61rrays\x18\x01 \x03(\x0b\x32\x16.modeltrain.NumpyArray\".\n\nFitRequest\x12 \n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x12.modeltrain.Matrix\"\x1f\n\x0b\x46itResponse\x12\x10\n\x08\x61\x63\x63uracy\x18\x01 \x01(\x02\"2\n\x0ePredictRequest\x12 \n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x12.modeltrain.Matrix\"=\n\x0fPredictResponse\x12*\n\nprediction\x18\x01 \x01(\x0b\x32\x16.modeltrain.NumpyArray2\x8e\x01\n\nModelTrain\x12:\n\x05train\x12\x16.modeltrain.FitRequest\x1a\x17.modeltrain.FitResponse\"\x00\x12\x44\n\x07predict\x12\x1a.modeltrain.PredictRequest\x1a\x1b.modeltrain.PredictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_train_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NUMPYARRAY']._serialized_start=33
  _globals['_NUMPYARRAY']._serialized_end=58
  _globals['_MATRIX']._serialized_start=60
  _globals['_MATRIX']._serialized_end=108
  _globals['_FITREQUEST']._serialized_start=110
  _globals['_FITREQUEST']._serialized_end=156
  _globals['_FITRESPONSE']._serialized_start=158
  _globals['_FITRESPONSE']._serialized_end=189
  _globals['_PREDICTREQUEST']._serialized_start=191
  _globals['_PREDICTREQUEST']._serialized_end=241
  _globals['_PREDICTRESPONSE']._serialized_start=243
  _globals['_PREDICTRESPONSE']._serialized_end=304
  _globals['_MODELTRAIN']._serialized_start=307
  _globals['_MODELTRAIN']._serialized_end=449
# @@protoc_insertion_point(module_scope)
