# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ping_pong.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ping_pong.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fping_pong.proto\x12\x0cpingponggprc\"\x18\n\x04Ping\x12\x10\n\x08mensagem\x18\x01 \x01(\t\"\'\n\x04Pong\x12\x10\n\x08mensagem\x18\x01 \x01(\t\x12\r\n\x05tempo\x18\x02 \x01(\x01\x32I\n\x08PingPong\x12=\n\x11GetServerResponse\x12\x12.pingponggprc.Ping\x1a\x12.pingponggprc.Pong\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ping_pong_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PING']._serialized_start=33
  _globals['_PING']._serialized_end=57
  _globals['_PONG']._serialized_start=59
  _globals['_PONG']._serialized_end=98
  _globals['_PINGPONG']._serialized_start=100
  _globals['_PINGPONG']._serialized_end=173
# @@protoc_insertion_point(module_scope)
